### ISSUE TITLE
p2p code review

### ISSUE THREAD

**Issue by VanessaAoki** [vichuge/rails_capstone_investments#2]
@vichuge, as usual, your project looks AMAZING!

Congratulations on creating such an organized repo in such a short time!

Keep up the great work!

**Comment by marilirulita** [comment]
Good job!
![gato](https://user-images.githubusercontent.com/50138343/111643925-9480c300-87bc-11eb-81ed-d3c307f0328a.gif)

I am practicing with the gifs, I found this funny one, lol!
